name: BlankSpace CI - Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.3.0
        with:
          activate-environment: blankspace
          environment-file: environment.yml
          auto-activate-base: false
          auto-update-conda: true
          channels: conda-forge, defaults
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pip install -e .
          pytest
